"""Conversion from Cirq circuits to Clifft circuit text."""

from __future__ import annotations

import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any

import cirq

# Used when matching resolved floating-point Cirq half-turn exponents to exact
# symbolic gates. Convention-sensitive mappings still get unitary coverage.
_ANGLE_ATOL = 1e-8


@dataclass(frozen=True)
class MeasurementMetadata:
    """Columns generated by one Cirq measurement key."""

    key: str
    qubits: tuple[cirq.Qid, ...]
    columns: tuple[int, ...]
    invert_mask: tuple[bool, ...]


@dataclass(frozen=True)
class ConvertedCircuit:
    """Clifft text plus metadata needed to map samples back to Cirq."""

    clifft_text: str
    qubit_map: Mapping[cirq.Qid, int]
    measurement_map: Mapping[str, MeasurementMetadata]


class UnsupportedCirqOperationError(ValueError):
    """Raised when a Cirq operation cannot be represented by the adapter."""

    def __init__(self, operation: cirq.Operation, reason: str) -> None:
        self.operation = operation
        self.reason = reason
        qubits = ", ".join(repr(qubit) for qubit in operation.qubits)
        location = f" on qubits ({qubits})" if qubits else ""
        super().__init__(f"Unsupported Cirq operation {operation!r}{location}: {reason}")


@dataclass
class _ConversionState:
    qubit_map: Mapping[cirq.Qid, int]
    lines: list[str]
    measurement_map: dict[str, MeasurementMetadata]
    measurement_count: int = 0


def to_clifft_text(
    circuit: cirq.AbstractCircuit,
    qubit_order: cirq.QubitOrderOrList | None = None,
) -> ConvertedCircuit:
    """Convert a resolved qubit-only Cirq circuit to Clifft circuit text.

    Args:
        circuit: Circuit to convert. Symbolic parameters must already be resolved.
        qubit_order: Optional explicit Cirq qubit order. When omitted, circuit
            qubits are sorted with Cirq's default ordering.

    Raises:
        ValueError: If the circuit has qudits, unresolved parameters, or an
            invalid explicit qubit order.
        UnsupportedCirqOperationError: If an operation cannot be represented.
    """

    _validate_circuit(circuit)
    ordered_qubits = _ordered_qubits(circuit, qubit_order)
    qubit_map = {qubit: index for index, qubit in enumerate(ordered_qubits)}
    state = _ConversionState(qubit_map=qubit_map, lines=[], measurement_map={})

    for operation in circuit.all_operations():
        _emit_operation(operation, state)

    return ConvertedCircuit(
        clifft_text="\n".join(state.lines),
        qubit_map=MappingProxyType(dict(qubit_map)),
        measurement_map=MappingProxyType(dict(state.measurement_map)),
    )


def _validate_circuit(circuit: cirq.AbstractCircuit) -> None:
    for qubit in circuit.all_qubits():
        dimension = getattr(qubit, "dimension", 2)
        if dimension != 2:
            raise ValueError(
                f"clifft-cirq only supports qubits; {qubit!r} has dimension {dimension}"
            )

    if cirq.is_parameterized(circuit):
        raise ValueError("clifft-cirq requires resolved Cirq parameters")


def _ordered_qubits(
    circuit: cirq.AbstractCircuit,
    qubit_order: cirq.QubitOrderOrList | None,
) -> tuple[cirq.Qid, ...]:
    qubits = tuple(circuit.all_qubits())
    if qubit_order is None:
        return tuple(sorted(qubits))

    order = cirq.QubitOrder.as_qubit_order(qubit_order)
    ordered = tuple(order.order_for(qubits))
    if len(ordered) != len(qubits) or set(ordered) != set(qubits):
        raise ValueError("qubit_order must contain exactly the circuit qubits")
    return ordered


def _emit_operation(operation: cirq.Operation, state: _ConversionState) -> None:
    if _is_global_phase_operation(operation):
        return

    if _is_measurement_operation(operation):
        _emit_measurement(operation, state)
        return

    direct_lines = _emit_direct_operation(operation, state.qubit_map)
    if direct_lines is not None:
        state.lines.extend(direct_lines)
        return

    try:
        decomposed = cirq.decompose(
            operation,
            keep=_is_clifft_emittable,
            on_stuck_raise=ValueError(
                f"operation is not in the supported Clifft subset: {operation!r}"
            ),
        )
    except Exception as exc:
        raise UnsupportedCirqOperationError(operation, str(exc)) from exc

    if len(decomposed) == 1 and decomposed[0] == operation:
        raise UnsupportedCirqOperationError(operation, "operation did not decompose")

    for decomposed_operation in decomposed:
        _emit_operation(decomposed_operation, state)


def _is_global_phase_operation(operation: cirq.Operation) -> bool:
    return len(operation.qubits) == 0


def _is_measurement_operation(operation: cirq.Operation) -> bool:
    return isinstance(operation.gate, cirq.MeasurementGate)


def _emit_measurement(operation: cirq.Operation, state: _ConversionState) -> None:
    gate = operation.gate
    if not isinstance(gate, cirq.MeasurementGate):
        raise AssertionError("_emit_measurement called for a non-measurement operation")

    if gate.confusion_map:
        raise UnsupportedCirqOperationError(
            operation,
            "measurement confusion_map is not supported in v1",
        )

    key = _measurement_key(gate)
    if key in state.measurement_map:
        raise UnsupportedCirqOperationError(
            operation,
            f"repeated measurement key {key!r} is not supported in v1",
        )

    invert_mask = _padded_invert_mask(gate, len(operation.qubits))
    targets = []
    for qubit, invert in zip(operation.qubits, invert_mask, strict=True):
        target = str(_target_index(qubit, state.qubit_map, operation))
        targets.append(f"!{target}" if invert else target)

    columns = tuple(range(state.measurement_count, state.measurement_count + len(operation.qubits)))
    state.measurement_count += len(operation.qubits)
    state.measurement_map[key] = MeasurementMetadata(
        key=key,
        qubits=tuple(operation.qubits),
        columns=columns,
        invert_mask=invert_mask,
    )
    state.lines.append(f"M {' '.join(targets)}")


def _measurement_key(gate: cirq.MeasurementGate) -> str:
    try:
        return str(cirq.measurement_key_name(gate))
    except TypeError:
        return str(gate.key)


def _padded_invert_mask(gate: cirq.MeasurementGate, width: int) -> tuple[bool, ...]:
    invert_mask = tuple(bool(value) for value in gate.invert_mask)
    if len(invert_mask) > width:
        raise ValueError(
            f"measurement invert_mask has length {len(invert_mask)}, expected at most {width}"
        )
    return invert_mask + (False,) * (width - len(invert_mask))


def _emit_direct_operation(
    operation: cirq.Operation,
    qubit_map: Mapping[cirq.Qid, int],
) -> list[str] | None:
    gate = operation.gate
    if gate is None:
        return None

    if cirq.is_parameterized(operation):
        raise UnsupportedCirqOperationError(operation, "operation has unresolved parameters")

    targets = tuple(_target_index(qubit, qubit_map, operation) for qubit in operation.qubits)
    if _is_identity_gate(gate):
        return []

    if _is_reset_gate(gate):
        return [f"R {_join_targets(targets)}"]

    if len(targets) == 1:
        emitted = _emit_single_qubit_gate(gate, targets[0])
        if emitted is not None:
            return emitted

    if len(targets) == 2:
        emitted = _emit_two_qubit_gate(gate, targets)
        if emitted is not None:
            return emitted

    if len(targets) == 3:
        emitted = _emit_three_qubit_gate(gate, targets)
        if emitted is not None:
            return emitted

    return None


def _is_clifft_emittable(operation: cirq.Operation) -> bool:
    if _is_global_phase_operation(operation) or _is_measurement_operation(operation):
        return True

    qubit_map = {qubit: index for index, qubit in enumerate(operation.qubits)}
    try:
        return _emit_direct_operation(operation, qubit_map) is not None
    except (TypeError, ValueError, UnsupportedCirqOperationError):
        return False


def _emit_single_qubit_gate(gate: cirq.Gate, target: int) -> list[str] | None:
    if _is_gate_type(gate, "HPowGate"):
        exponent = _gate_exponent(gate)
        if _periodic_close(exponent, 0.0):
            return []
        if _periodic_close(exponent, 1.0):
            return [f"H {target}"]
        return None

    if _is_gate_type(gate, "XPowGate"):
        return _emit_single_axis_pow("X", _gate_exponent(gate), target)
    if _is_gate_type(gate, "YPowGate"):
        return _emit_single_axis_pow("Y", _gate_exponent(gate), target)
    if _is_gate_type(gate, "ZPowGate"):
        return _emit_single_axis_pow("Z", _gate_exponent(gate), target)

    return None


def _emit_single_axis_pow(axis: str, exponent: float, target: int) -> list[str]:
    if _periodic_close(exponent, 0.0):
        return []
    if _periodic_close(exponent, 1.0):
        return [f"{axis} {target}"]

    if axis == "Z":
        if _periodic_close(exponent, 0.5):
            return [f"S {target}"]
        if _periodic_close(exponent, -0.5):
            return [f"S_DAG {target}"]
        if _periodic_close(exponent, 0.25):
            return [f"T {target}"]
        if _periodic_close(exponent, -0.25):
            return [f"T_DAG {target}"]

    return [f"R_{axis}({_format_float(exponent)}) {target}"]


def _emit_two_qubit_gate(gate: cirq.Gate, targets: tuple[int, int]) -> list[str] | None:
    a, b = targets

    if _is_gate_type(gate, "CXPowGate"):
        return _emit_powered_named_gate("CX", _gate_exponent(gate), targets)
    if _is_gate_type(gate, "CZPowGate"):
        return _emit_cz_pow(_gate_exponent(gate), targets)
    if _is_gate_type(gate, "SwapPowGate"):
        return _emit_powered_named_gate("SWAP", _gate_exponent(gate), targets)

    if _is_gate_type(gate, "ISwapPowGate"):
        exponent = _gate_exponent(gate)
        if _periodic_close(exponent, 0.0, period=4.0):
            return []
        if _periodic_close(exponent, 1.0, period=4.0):
            return [f"ISWAP {a} {b}"]
        if _periodic_close(exponent, -1.0, period=4.0):
            return [f"ISWAP_DAG {a} {b}"]
        return None

    if _is_gate_type(gate, "XXPowGate"):
        return _emit_two_axis_pow("XX", _gate_exponent(gate), targets)
    if _is_gate_type(gate, "YYPowGate"):
        return _emit_two_axis_pow("YY", _gate_exponent(gate), targets)
    if _is_gate_type(gate, "ZZPowGate"):
        return _emit_two_axis_pow("ZZ", _gate_exponent(gate), targets)

    if _is_controlled_h_gate(gate):
        return [f"CH {a} {b}"]

    return None


def _emit_powered_named_gate(
    clifft_name: str,
    exponent: float,
    targets: Sequence[int],
) -> list[str] | None:
    if _periodic_close(exponent, 0.0):
        return []
    if _periodic_close(exponent, 1.0):
        return [f"{clifft_name} {_join_targets(targets)}"]
    return None


def _emit_cz_pow(exponent: float, targets: tuple[int, int]) -> list[str]:
    a, b = targets
    if _periodic_close(exponent, 0.0):
        return []
    if _periodic_close(exponent, 1.0):
        return [f"CZ {a} {b}"]

    half_exponent = exponent / 2
    return [
        *_emit_single_axis_pow("Z", half_exponent, a),
        *_emit_single_axis_pow("Z", half_exponent, b),
        *_emit_two_axis_pow("ZZ", -half_exponent, targets),
    ]


def _emit_two_axis_pow(axis: str, exponent: float, targets: tuple[int, int]) -> list[str]:
    a, b = targets
    if _periodic_close(exponent, 0.0):
        return []
    return [f"R_{axis}({_format_float(exponent)}) {a} {b}"]


def _emit_three_qubit_gate(gate: cirq.Gate, targets: tuple[int, int, int]) -> list[str] | None:
    exponent = getattr(gate, "exponent", None)
    if exponent is None:
        return None

    gate_name = type(gate).__name__
    if gate_name == "CCXPowGate":
        return _emit_powered_named_gate("CCX", _gate_exponent(gate), targets)
    if gate_name == "CCZPowGate":
        return _emit_powered_named_gate("CCZ", _gate_exponent(gate), targets)
    return None


def _is_identity_gate(gate: cirq.Gate) -> bool:
    return _is_gate_type(gate, "IdentityGate")


def _is_reset_gate(gate: cirq.Gate) -> bool:
    return _is_gate_type(gate, "ResetChannel")


def _is_controlled_h_gate(gate: cirq.Gate) -> bool:
    if not _is_gate_type(gate, "ControlledGate"):
        return False
    if not _has_default_control_values(gate):
        return False
    sub_gate = getattr(gate, "sub_gate", None)
    if sub_gate is None:
        return False
    return (
        _is_gate_type(sub_gate, "HPowGate")
        and _periodic_close(_gate_exponent(sub_gate), 1.0)
        and _has_trivial_global_phase(sub_gate)
    )


def _has_trivial_global_phase(gate: cirq.Gate) -> bool:
    global_shift = float(getattr(gate, "global_shift", 0.0))
    exponent = _gate_exponent(gate)
    return _periodic_close(global_shift * exponent, 0.0, period=2.0)


def _has_default_control_values(gate: cirq.Gate) -> bool:
    control_values = getattr(gate, "control_values", None)
    if control_values is None:
        return True
    try:
        return all(tuple(value) == (1,) for value in control_values)
    except TypeError:
        return False


def _is_gate_type(gate: Any, type_name: str) -> bool:
    cls = getattr(cirq, type_name, None)
    if cls is not None and isinstance(gate, cls):
        return True
    return type(gate).__name__ == type_name


def _gate_exponent(gate: cirq.Gate) -> float:
    exponent = getattr(gate, "exponent")
    return float(exponent)


def _periodic_close(value: float, target: float, period: float = 2.0) -> bool:
    return abs(math.remainder(value - target, period)) <= _ANGLE_ATOL


def _format_float(value: float) -> str:
    if abs(value) <= _ANGLE_ATOL:
        value = 0.0
    nearest_int = round(value)
    if abs(value - nearest_int) <= _ANGLE_ATOL:
        return str(nearest_int)
    return f"{value:.12g}"


def _join_targets(targets: Sequence[int]) -> str:
    return " ".join(str(target) for target in targets)


def _target_index(
    qubit: cirq.Qid,
    qubit_map: Mapping[cirq.Qid, int],
    operation: cirq.Operation,
) -> int:
    try:
        return qubit_map[qubit]
    except KeyError as exc:
        raise UnsupportedCirqOperationError(
            operation,
            f"operation introduced qubit {qubit!r} outside the circuit qubit map",
        ) from exc
